import { Component } from '@angular/core';

interface Rule {
    name: string;
    enabled: boolean;
    output: {
        type: 'cc' | 'program' | 'note';
        channel: number;
        ccNumber: number;
        valueMode: 'constant' | 'trigger';
        constantValue: number;
        bank: number;
        program: number;
        note: number;
        velocity: number;
        velocityMode: 'constant' | 'trigger';
        delayMs: number;
    };
    trigger: {
        type: 'noteOn' | 'controlChange';
        channel: number;
        noteMode: 'specific' | 'any';
        specificNote: number;
        ccNumber: number;
        valueMode: 'specific' | 'any';
        specificValue: number;
        consume: 'eat' | 'pass';
    };
}

@Component({
    selector: 'app-streambyter',
    templateUrl: './streambyter.component.html',
    styleUrls: ['./streambyter.component.scss'],
    standalone: false,
})
export class StreambyterComponent {
    rules: Rule[] = [];
    generatedScript: string = '';
    showGenerated: boolean = false;
    fileName: string = '';
    
    importFileInputId = 'importRulesInput';
    
    exampleRules: Rule[] = [
        {
            name: "CC to Note",
            enabled: true,
            output: {
                type: "note",
                channel: 1,
                ccNumber: 0,
                valueMode: "constant",
                constantValue: 0,
                bank: 0,
                program: 0,
                note: 60,
                velocity: 100,
                velocityMode: "constant",
                delayMs: 0
            },
            trigger: {
                type: "controlChange",
                channel: 1,
                noteMode: "specific",
                specificNote: 60,
                ccNumber: 7,
                valueMode: "any",
                specificValue: 0,
                consume: "eat"
            }
        },
        {
            name: "Note Velocity Scale",
            enabled: true,
            output: {
                type: "cc",
                channel: 2,
                ccNumber: 11,
                valueMode: "trigger",
                constantValue: 0,
                bank: 0,
                program: 0,
                note: 60,
                velocity: 64,
                velocityMode: "trigger",
                delayMs: 0
            },
            trigger: {
                type: "noteOn",
                channel: 2,
                noteMode: "any",
                specificNote: 60,
                ccNumber: 0,
                valueMode: "any",
                specificValue: 0,
                consume: "pass"
            }
        }
    ];
    
    triggerFileInput() {
        const input = document.getElementById(this.importFileInputId) as HTMLInputElement;
        if (input) input.click();
    }
    
    loadExample() {
        this.rules = JSON.parse(JSON.stringify(this.exampleRules));
    }
    
    clearRules() {
        this.rules = [];
        this.showGenerated = false;
        this.generatedScript = '';
        this.fileName = '';
    }
    
    addRule() {
        const newRule: Rule = {
            name: "New Rule",
            enabled: true,
            output: {
                type: "cc",
                channel: 1,
                ccNumber: 0,
                valueMode: "constant",
                constantValue: 0,
                bank: 0,
                program: 0,
                note: 60,
                velocity: 64,
                velocityMode: "constant",
                delayMs: 0
            },
            trigger: {
                type: "noteOn",
                channel: 1,
                noteMode: "specific",
                specificNote: 60,
                ccNumber: 0,
                valueMode: "any",
                specificValue: 0,
                consume: "eat"
            }
        };
        this.rules.push(newRule);
    }
    
    deleteRule(index: number) {
        this.rules.splice(index, 1);
    }
    
    // Полностью переписанный метод генерации скрипта
    generateStreamByterScript() {
        const lines: string[] = [];
    
        lines.push('# StreamByter Script generated by MIDI Messenger');
        lines.push(`# Generated: ${new Date().toLocaleString()}`);
        lines.push(`# Total rules: ${this.rules.length}`);
        lines.push('');
    
        const enabledRules = this.rules.filter(r => r.enabled);
    
        if (enabledRules.length === 0) {
            lines.push('# No enabled rules');
            this.generatedScript = lines.join('\n');
            this.showGenerated = true;
            return;
        }
    
        // INITIALIZATION section (IF LOAD)
        lines.push('# ========== INITIALIZATION ==========');
        lines.push('IF LOAD');
    
        enabledRules.forEach((rule, index) => {
            lines.push(`  # Rule ${index + 1}: ${rule.name}`);
            // Инициализация переменных для правил
            lines.push(`  ASS K${index} = 0`);
        });
    
        lines.push('END');
        lines.push('');
    
        // RULES section
        enabledRules.forEach((rule, index) => {
            lines.push(`# ========== RULE ${index + 1}: ${rule.name} ==========`);
        
            // Генерируем правило в формате StreamByter I (более простой и надежный)
            const ruleLine = this.generateStreamByterIRule(rule);
            if (ruleLine) {
                lines.push(ruleLine);
            }
        
            lines.push('');
        });
    
        this.generatedScript = lines.join('\n');
        this.showGenerated = true;
    }

    // Генерация правил в формате StreamByter I (совместим с StreamByter II)
    private generateStreamByterIRule(rule: Rule): string {
        // Формируем левую часть (триггер)
        let triggerPattern = '';
    
        if (rule.trigger.type === 'noteOn') {
            // Note On: 9X (X - канал)
            const channelNibble = (rule.trigger.channel - 1).toString(16).toUpperCase();
            triggerPattern = `9${channelNibble}`;
        
            if (rule.trigger.noteMode === 'specific') {
                const noteHex = rule.trigger.specificNote.toString(16).toUpperCase().padStart(2, '0');
                triggerPattern += ` ${noteHex}`;
            } else {
                triggerPattern += ` XX`;
            }
        
            // Для Note On, можно также добавить условие на velocity (опционально)
            triggerPattern += ` XX`; // Любая velocity
        } 
        else if (rule.trigger.type === 'controlChange') {
            // Control Change: BX
            const channelNibble = (rule.trigger.channel - 1).toString(16).toUpperCase();
            triggerPattern = `B${channelNibble}`;
        
            // CC номер
            const ccHex = rule.trigger.ccNumber.toString(16).toUpperCase().padStart(2, '0');
            triggerPattern += ` ${ccHex}`;
        
            // Значение CC
            if (rule.trigger.valueMode === 'specific') {
                const valueHex = rule.trigger.specificValue.toString(16).toUpperCase().padStart(2, '0');
                triggerPattern += ` ${valueHex}`;
            } else {
                triggerPattern += ` XX`; // Любое значение
            }
        }
    
        // Формируем правую часть (выход)
        let outputPattern = '';
        let flags = '';
    
        if (rule.output.type === 'cc') {
            const channelNibble = (rule.output.channel - 1).toString(16).toUpperCase();
            outputPattern = `B${channelNibble}`;
        
            const ccHex = rule.output.ccNumber.toString(16).toUpperCase().padStart(2, '0');
            outputPattern += ` ${ccHex}`;
        
            if (rule.output.valueMode === 'constant') {
                const valueHex = rule.output.constantValue.toString(16).toUpperCase().padStart(2, '0');
                outputPattern += ` ${valueHex}`;
            } else {
                outputPattern += ` XX`; // Сохраняем оригинальное значение
            }
        } 
        else if (rule.output.type === 'note') {
            const channelNibble = (rule.output.channel - 1).toString(16).toUpperCase();
            outputPattern = `9${channelNibble}`;
        
            const noteHex = rule.output.note.toString(16).toUpperCase().padStart(2, '0');
            outputPattern += ` ${noteHex}`;
        
            if (rule.output.velocityMode === 'constant') {
                const velocityHex = rule.output.velocity.toString(16).toUpperCase().padStart(2, '0');
                outputPattern += ` ${velocityHex}`;
            } else {
                outputPattern += ` XX`; // Сохраняем оригинальную velocity
            }
        } 
        else if (rule.output.type === 'program') {
            const channelNibble = (rule.output.channel - 1).toString(16).toUpperCase();
            outputPattern = `C${channelNibble}`;
        
            const programHex = rule.output.program.toString(16).toUpperCase().padStart(2, '0');
            outputPattern += ` ${programHex}`;
        }
    
        // Добавляем флаги
        if (rule.trigger.consume === 'eat') {
            flags = ' +B'; // Block original message
        }
    
        if (rule.output.delayMs > 0) {
            flags += ` +D${rule.output.delayMs}`;
        }
    
        // Для trigger value mode 'any' и output value mode 'trigger' используем clone
        if (rule.trigger.valueMode === 'any' && rule.output.valueMode === 'trigger') {
            flags += ' +C'; // Clone message
        }
    
        return `${triggerPattern} = ${outputPattern}${flags}`;
    }

    // Альтернативный метод для сложных правил с использованием StreamByter II синтаксиса
    private generateStreamByterIIRule(rule: Rule): string[] {
        const lines: string[] = [];
    
        // Условие
        if (rule.trigger.type === 'noteOn') {
            const channelHex = (rule.trigger.channel - 1).toString(16).toUpperCase();
            lines.push(`IF M0 == 9${channelHex}`);
        
            if (rule.trigger.noteMode === 'specific') {
                const noteHex = rule.trigger.specificNote.toString(16).toUpperCase().padStart(2, '0');
                lines.push(`  IF M1 == ${noteHex}`);
            }
        
            // Действие
            if (rule.output.type === 'cc') {
                const outChannel = (rule.output.channel - 1).toString(16).toUpperCase();
                const ccHex = rule.output.ccNumber.toString(16).toUpperCase().padStart(2, '0');
            
                if (rule.output.valueMode === 'constant') {
                    const valueHex = rule.output.constantValue.toString(16).toUpperCase().padStart(2, '0');
                    lines.push(`    ASS M0 = B${outChannel}`);
                    lines.push(`    ASS M1 = ${ccHex}`);
                    lines.push(`    ASS M2 = ${valueHex}`);
                } else {
                    lines.push(`    ASS M0 = B${outChannel}`);
                    lines.push(`    ASS M1 = ${ccHex}`);
                    // M2 оставляем как есть
                }
            } else if (rule.output.type === 'note') {
                const outChannel = (rule.output.channel - 1).toString(16).toUpperCase();
                const noteHex = rule.output.note.toString(16).toUpperCase().padStart(2, '0');
            
                if (rule.output.velocityMode === 'constant') {
                    const velHex = rule.output.velocity.toString(16).toUpperCase().padStart(2, '0');
                    lines.push(`    ASS M0 = 9${outChannel}`);
                    lines.push(`    ASS M1 = ${noteHex}`);
                    lines.push(`    ASS M2 = ${velHex}`);
                } else {
                    lines.push(`    ASS M0 = 9${outChannel}`);
                    lines.push(`    ASS M1 = ${noteHex}`);
                    // M2 оставляем как есть
                }
            }
        
            if (rule.trigger.consume === 'eat') {
                lines.push(`    BLOCK`);
            }
        
            lines.push(`  END`);
            lines.push(`END`);
        } 
        else if (rule.trigger.type === 'controlChange') {
            const channelHex = (rule.trigger.channel - 1).toString(16).toUpperCase();
            const ccHex = rule.trigger.ccNumber.toString(16).toUpperCase().padStart(2, '0');
        
            lines.push(`IF M0 == B${channelHex}`);
            lines.push(`  IF M1 == ${ccHex}`);
        
            if (rule.trigger.valueMode === 'specific') {
                const valHex = rule.trigger.specificValue.toString(16).toUpperCase().padStart(2, '0');
                lines.push(`    IF M2 == ${valHex}`);
            }
        
            // Действие
            if (rule.output.type === 'cc') {
                const outChannel = (rule.output.channel - 1).toString(16).toUpperCase();
                const outCcHex = rule.output.ccNumber.toString(16).toUpperCase().padStart(2, '0');
            
                if (rule.output.valueMode === 'constant') {
                    const valHex = rule.output.constantValue.toString(16).toUpperCase().padStart(2, '0');
                    lines.push(`      ASS M0 = B${outChannel}`);
                    lines.push(`      ASS M1 = ${outCcHex}`);
                    lines.push(`      ASS M2 = ${valHex}`);
                } else {
                    lines.push(`      ASS M0 = B${outChannel}`);
                    lines.push(`      ASS M1 = ${outCcHex}`);
                    // M2 оставляем как есть
                }
            } else if (rule.output.type === 'note') {
                const outChannel = (rule.output.channel - 1).toString(16).toUpperCase();
                const noteHex = rule.output.note.toString(16).toUpperCase().padStart(2, '0');
            
                if (rule.output.velocityMode === 'constant') {
                    const velHex = rule.output.velocity.toString(16).toUpperCase().padStart(2, '0');
                    lines.push(`      ASS M0 = 9${outChannel}`);
                    lines.push(`      ASS M1 = ${noteHex}`);
                    lines.push(`      ASS M2 = ${velHex}`);
                } else {
                    lines.push(`      ASS M0 = 9${outChannel}`);
                    lines.push(`      ASS M1 = ${noteHex}`);
                    // M2 оставляем как есть
                }
            }
        
            if (rule.trigger.consume === 'eat') {
                lines.push(`      BLOCK`);
            }
        
            if (rule.trigger.valueMode === 'specific') {
                lines.push(`    END`);
            }
            lines.push(`  END`);
            lines.push(`END`);
        }
    
        return lines;
    }
    
    private generateTriggerCondition(trigger: any, ruleIndex: number): string {
        if (trigger.type === 'noteOn') {
            const channelHex = (trigger.channel - 1).toString(16);
            const statusByte = `9${channelHex}`;
            
            if (trigger.noteMode === 'specific') {
                const noteHex = trigger.specificNote.toString(16).toUpperCase().padStart(2, '0');
                return `IF M0 == 0x${statusByte}\n  IF M1 == 0x${noteHex}`;
            } else {
                return `IF M0 == 0x${statusByte}`;
            }
        } else if (trigger.type === 'controlChange') {
            const channelHex = (trigger.channel - 1).toString(16);
            const statusByte = `B${channelHex}`;
            const ccHex = trigger.ccNumber.toString(16).toUpperCase().padStart(2, '0');
            
            if (trigger.valueMode === 'specific') {
                const valueHex = trigger.specificValue.toString(16).toUpperCase().padStart(2, '0');
                return `IF M0 == 0x${statusByte}\n  IF M1 == 0x${ccHex}\n    IF M2 == 0x${valueHex}`;
            } else {
                return `IF M0 == 0x${statusByte}\n  IF M1 == 0x${ccHex}`;
            }
        }
        
        return '';
    }
    
    private generateOutputActions(output: any): string[] {
        const actions: string[] = [];
        
        if (output.type === 'cc') {
            const channelHex = (output.channel - 1).toString(16);
            const statusByte = `B${channelHex}`;
            const ccHex = output.ccNumber.toString(16).toUpperCase().padStart(2, '0');
            
            if (output.valueMode === 'constant') {
                const valueHex = output.constantValue.toString(16).toUpperCase().padStart(2, '0');
                actions.push(`ASS M0 = 0x${statusByte}`);
                actions.push(`ASS M1 = 0x${ccHex}`);
                actions.push(`ASS M2 = 0x${valueHex}`);
            } else if (output.valueMode === 'trigger') {
                actions.push(`ASS M0 = 0x${statusByte}`);
                actions.push(`ASS M1 = 0x${ccHex}`);
                actions.push(`# M2 keeps original value`);
            }
        } else if (output.type === 'note') {
            const channelHex = (output.channel - 1).toString(16);
            const statusByte = `9${channelHex}`;
            const noteHex = output.note.toString(16).toUpperCase().padStart(2, '0');
            
            if (output.velocityMode === 'constant') {
                const velocityHex = output.velocity.toString(16).toUpperCase().padStart(2, '0');
                actions.push(`ASS M0 = 0x${statusByte}`);
                actions.push(`ASS M1 = 0x${noteHex}`);
                actions.push(`ASS M2 = 0x${velocityHex}`);
            } else if (output.velocityMode === 'trigger') {
                actions.push(`ASS M0 = 0x${statusByte}`);
                actions.push(`ASS M1 = 0x${noteHex}`);
                actions.push(`# M2 keeps original velocity`);
            }
        } else if (output.type === 'program') {
            const channelHex = (output.channel - 1).toString(16);
            const statusByte = `C${channelHex}`;
            const programHex = output.program.toString(16).toUpperCase().padStart(2, '0');
            
            actions.push(`ASS M0 = 0x${statusByte}`);
            actions.push(`ASS M1 = 0x${programHex}`);
        }
        
        return actions;
    }
    
    copyToClipboard() {
        navigator.clipboard.writeText(this.generatedScript).then(() => {
            alert('Script copied to clipboard!');
        }).catch(() => {
            alert('Failed to copy script');
        });
    }
    
    private getFormattedDate(): string {
        const now = new Date();
        const year = now.getFullYear();
        const month = String(now.getMonth() + 1).padStart(2, '0');
        const day = String(now.getDate()).padStart(2, '0');
        const hours = String(now.getHours()).padStart(2, '0');
        const minutes = String(now.getMinutes()).padStart(2, '0');
        
        return `${year}-${month}-${day}__${hours}-${minutes}`;
    }
    
    generatePlistContent(script: string): string {
        // Экранируем только необходимые XML-спецсимволы
        let escapedScript = script
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;');
        
        return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>StreamByter-Rules</key>
    <string>${escapedScript}</string>
</dict>
</plist>`;
    }
    
    downloadScript() {
        if (!this.generatedScript) {
            alert('Please generate a script first!');
            return;
        }
        
        let finalFileName = this.fileName.trim();
        if (!finalFileName) {
            finalFileName = this.getFormattedDate();
        }
        
        if (!finalFileName.endsWith('.sbr')) {
            finalFileName += '.sbr';
        }
        
        const plistContent = this.generatePlistContent(this.generatedScript);
        
        const blob = new Blob([plistContent], { type: 'application/xml' });
        const a = document.createElement('a');
        a.href = URL.createObjectURL(blob);
        a.download = finalFileName;
        a.click();
        URL.revokeObjectURL(a.href);
    }
    
    downloadAsJson() {
        if (!this.generatedScript) {
            alert('Please generate a script first!');
            return;
        }
        
        let finalFileName = this.fileName.trim();
        if (!finalFileName) {
            finalFileName = this.getFormattedDate();
        }
        
        if (!finalFileName.endsWith('.json')) {
            finalFileName += '.json';
        }
        
        const jsonContent = {
            script: this.generatedScript,
            generated: new Date().toISOString(),
            rulesCount: this.rules.length
        };
        
        const blob = new Blob([JSON.stringify(jsonContent, null, 2)], { type: 'application/json' });
        const a = document.createElement('a');
        a.href = URL.createObjectURL(blob);
        a.download = finalFileName;
        a.click();
        URL.revokeObjectURL(a.href);
    }
    
    onFileSelected(event: Event) {
        const input = event.target as HTMLInputElement;
        if (!input.files?.length) return;
        
        const file = input.files[0];
        const reader = new FileReader();
        reader.onload = (e) => {
            try {
                const json = JSON.parse(e.target?.result as string);
                if (json.rules) {
                    this.rules = this.convertFromExternal(json.rules);
                    alert(`Loaded ${this.rules.length} rules from file!`);
                }
            } catch (ex) {
                alert('Invalid JSON file');
            }
        };
        reader.readAsText(file);
        input.value = '';
    }
    
    private convertFromExternal(externalRules: any[]): Rule[] {
        return externalRules.map(ext => ({
            name: ext.name || 'Imported Rule',
            enabled: ext.enabled !== false,
            output: {
                type: 'cc',
                channel: 1,
                ccNumber: 0,
                valueMode: 'constant',
                constantValue: 0,
                bank: 0,
                program: 0,
                note: 60,
                velocity: 64,
                velocityMode: 'constant',
                delayMs: 0
            },
            trigger: {
                type: 'noteOn',
                channel: 1,
                noteMode: 'any',
                specificNote: 60,
                ccNumber: 0,
                valueMode: 'any',
                specificValue: 0,
                consume: 'eat'
            }
        }));
    }
}